Allow erroring modules. Always cache providers

diff --git a/.github/workflows/pipelines-drift-detection.yml b/.github/workflows/pipelines-drift-detection.yml
--- a/.github/workflows/pipelines-drift-detection.yml
+++ b/.github/workflows/pipelines-drift-detection.yml
@@ -49,9 +49,9 @@ jobs:
           path: infra-live-repo
           fetch-depth: 0
 
-      - name: Cache Providers
-        id: cache-providers
-        uses: actions/cache@v4
+      - name: Cache Providers Restore
+        id: cache-providers-restore
+        uses: actions/cache/restore@v4
         with:
           path: ~/.cache/terragrunt/providers
           key: ${{ runner.os }}-terragrunt-providers
@@ -117,6 +117,7 @@ jobs:
           GRUNTWORK_CONFIG_FILE: ${{ steps.gruntwork_context.outputs.gruntwork_config_file }}
         shell: bash
         run: |
+          set -euo pipefail
           if [ "$TF_BINARY" == "terraform" ]
           then
             export TERRAGRUNT_TFPATH=terraform
@@ -132,6 +133,7 @@ jobs:
           for path in "${paths[@]}"; do
             echo "Running plan for $path"
             terragrunt_command="run-all plan --terragrunt-exclude-dir=. --terragrunt-include-dir=$path"
+            set +e
             pipelines execute terragrunt \
               --working-directory . \
               --infra-live-repo . \
@@ -140,7 +142,20 @@ jobs:
               --gruntwork-config-file "$GRUNTWORK_CONFIG_FILE" \
               --out-dir "$plan_folder" \
               --command "$terragrunt_command"
+            pipelines_exit_code=$?
+            set -e
+            if [[ $pipelines_exit_code -ne 0 ]]; then
+              echo "::error::Error running plan for $path"
+            fi
           done
+
+      - name: Cache Providers Save
+        id: cache-providers-save
+        uses: actions/cache/save@v4
+        if: always()
+        with:
+          path: ~/.cache/terragrunt/providers
+          key: ${{ steps.cache-providers-restore.outputs.cache-primary-key }}
 
       - name: Clean repo
         id: clean-repo
