chore: simplify delete procedure

diff --git a/.github/workflows/pipelines-unlock.yml b/.github/workflows/pipelines-unlock.yml
--- a/.github/workflows/pipelines-unlock.yml
+++ b/.github/workflows/pipelines-unlock.yml
@@ -180,13 +180,9 @@ jobs:
             export AWS_SECRET_ACCESS_KEY=$(jq -r '.awsCredentials.SECRET_ACCESS_KEY' <<< $auth)
             export AWS_SESSION_TOKEN=$(jq -r '.awsCredentials.SESSION_TOKEN' <<< $auth)
 
-            echo "Fetching table status..."
-            TABLE_STATUS=$(aws dynamodb describe-table --table-name "terraform-locks" --query "Table.TableStatus" --output text 2>&1 || true)
-            echo $TABLE_STATUS
-            if [[ "$TABLE_STATUS" == "ACTIVE" ]]; then
-              aws dynamodb delete-table --table-name terraform-locks || true # Ignore failures if no table already exists
-            fi
-            echo "Lock removed, adding $working_dir to list of folders needing a rerun of terragrunt init" || true
+            aws dynamodb delete-table --table-name terraform-locks || true # Ignore failures if no table already exists
+
+            echo "Lock removed for $ACCOUNTID"
           }
 
 
