chore: ignore failures

diff --git a/.github/workflows/pipelines-unlock.yml b/.github/workflows/pipelines-unlock.yml
--- a/.github/workflows/pipelines-unlock.yml
+++ b/.github/workflows/pipelines-unlock.yml
@@ -141,18 +141,20 @@ jobs:
             echo ACCOUNTID="$ACCOUNTID"
             REGION=$(echo $pipelinesConfigAuth | jq -r ".Authentication.AWSOIDC.Region")
             echo REGION="$REGION"
-  
+
             if containsElement $ACCOUNTID "${COMPLETED_ACCOUNTS[@]}"; then
               echo "Skipping $ACCOUNTID as it has already been processed"
               continue
+            else
+              echo "Unlocking state in $ACCOUNTID"
             fi
-            
+
             auth=$(pipelines auth terragrunt-credentials --ci github-actions --cloud aws --wd .)
             export AWS_DEFAULT_REGION=$REGION
             export AWS_ACCESS_KEY_ID=$(echo $auth | jq -r '.awsCredentials.ACCESS_KEY_ID')
             export AWS_SECRET_ACCESS_KEY=$(echo $auth | jq -r '.awsCredentials.SECRET_ACCESS_KEY')
             export AWS_SESSION_TOKEN=$(echo $auth | jq -r '.awsCredentials.SESSION_TOKEN')
-            aws dynamodb delete-table --table-name terraform-locks
+            aws dynamodb delete-table --table-name terraform-locks || true # Ignore failures if no table already exists
             terragrunt init
             COMPLETED_ACCOUNTS+=($ACCOUNTID)
             cd -
