moreeee

diff --git a/.github/workflows/pipelines.yml b/.github/workflows/pipelines.yml
--- a/.github/workflows/pipelines.yml
+++ b/.github/workflows/pipelines.yml
@@ -1,5 +1,5 @@
 name: Pipelines Execute
-run-name: Run ${{ inputs.terragrunt_command }} on ${{ inputs.working_directory }}
+run-name: Run Gruntwork Pipelines
 on:
   workflow_call:
     inputs:
@@ -11,23 +11,6 @@ on:
         description: "The folder path in which the command will run"
         required: true
         type: string
-      account:
-        description: "The AWS Account ID of the ultimate account we will take action on"
-        required: true
-        type: string
-      terragrunt_command:
-        type: string
-        description: "The terragrunt command to run"
-        required: true
-        default: "plan"
-      child_account_id:
-        description: "The AWS Account ID of the child account"
-        required: false
-        type: string
-      role_prefix:
-        description: "The role prefix to use when assuming roles in the account"
-        required: true
-        type: string
     secrets:
       GRUNTWORK_CODE_ACCESS_TOKEN:
         required: true
@@ -36,9 +19,31 @@ env:
   DEPLOY_BRANCH_NAME: main
 
 jobs:
+  # See https://stackoverflow.com/a/76151412
+  check_if_branch_is_ahead_of_main:
+    name: Check if branch is ahead of main
+    runs-on: ubuntu-latest
+    needs: [preflight_checks]
+    steps:
+      - uses: actions/checkout@v4
+        # Only run if this is a pull request and the target branch is main
+        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' }}
+        with:
+          fetch-depth: 0
+      - name: Check if branch is ahead of main
+        # Only run if this is a pull request and the target branch is main
+        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' }}
+        env:
+          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
+        run: |
+          if ! git merge-base --is-ancestor origin/main "$HEAD_SHA"; then
+            echo "::error::Branch is not up to date with main"
+            exit 1
+          fi
   detect_changes:
     name: Detect Infrastructure Changes
     runs-on: ubuntu-latest
+    needs: [check_if_branch_is_ahead_of_main]
     steps:
       - uses: actions/checkout@v4
         with:
