chore: run in series for now to avoid blowing up actions

diff --git a/.github/workflows/pipelines-unlock.yml b/.github/workflows/pipelines-unlock.yml
--- a/.github/workflows/pipelines-unlock.yml
+++ b/.github/workflows/pipelines-unlock.yml
@@ -184,10 +184,9 @@ jobs:
 
             for region in ${REGIONS[@]}; do
               echo "Deleting table terraform-locks in $region for $ACCOUNTID"
-              aws dynamodb delete-table --table-name terraform-locks --region $region || true & # Ignore failures if no table already exists
+              aws dynamodb delete-table --table-name terraform-locks --region $region || true  # Ignore failures if no table already exists
             done
 
-            wait
             echo "Lock removed for $ACCOUNTID"
           }
 
