Install terragrunt before stack generate

diff --git a/.github/workflows/pipelines-unlock.yml b/.github/workflows/pipelines-unlock.yml
--- a/.github/workflows/pipelines-unlock.yml
+++ b/.github/workflows/pipelines-unlock.yml
@@ -95,13 +95,51 @@ jobs:
           terragrunt_command: "force-unlock -force ${{ inputs.lock_id }}"
           branch: 'main'
 
+      - name: Setup Mise Toml
+        id: mise-toml
+        # working-directory: ./infra-live-repo
+        shell: bash
+        env:
+          GENERATE_MISE_TOML: ${{ inputs.generate_mise_toml }}
+          INFRA_LIVE_DIRECTORY: "./infra-live-repo"
+          TG_VERSION: 0.77.5
+          # TF_BINARY: ${{ inputs.tf_binary }}
+        run: |
+          if [[ "$GENERATE_MISE_TOML" == "true" ]] || [[ ! -f "$INFRA_LIVE_DIRECTORY/.mise.toml" ]]; then
+            if [[ ! -f "$INFRA_LIVE_DIRECTORY/.mise.toml" ]]; then
+              echo 'User does not have a `.mise.toml` file, generating one to avoid failure'
+            fi
+            echo 'TOML<<EOF' >> "$GITHUB_OUTPUT"
+            echo '[tools]' >> "$GITHUB_OUTPUT"
+            echo "$TF_BINARY = \"$TF_VERSION\"" >> "$GITHUB_OUTPUT"
+            echo "terragrunt = \"$TG_VERSION\"" >> "$GITHUB_OUTPUT"
+            echo 'EOF' >> "$GITHUB_OUTPUT"
+          else
+            echo 'TOML<<EOF' >> "$GITHUB_OUTPUT"
+            cat $INFRA_LIVE_DIRECTORY/.mise.toml >> "$GITHUB_OUTPUT"
+            echo '' >> "$GITHUB_OUTPUT"
+            echo 'EOF' >> "$GITHUB_OUTPUT"
+          fi
+
+      - uses: jdx/mise-action@v2
+        with:
+          install: true
+          cache: true
+          version: 2024.10.8
+          mise_toml: "${{ steps.mise-toml.outputs.TOML }}"
+
+      - name: Test Terraform, OpenTofu and Terragrunt
+        shell: bash
+        run: |
+          tofu --version || true
+          terraform --version || true
+          terragrunt --version
+
       - name: "Run terragrunt stack generate in ${{ inputs.working_directory }}"
         id: terragrunt_stack_generate
         if: ${{ inputs.stack_path }}
+        working-directory: ./infra-live-repo
         run: |
-          echo "pwd: $(pwd)"
-          ls -la
-          cd infra-live-repo
           stackDir=$(dirname ${{ inputs.stack_path }})
           cd $stackDir
           pipelinesConfigAuth=$(pipelines config auth)
