fix: clear ALL the tables

diff --git a/.github/workflows/pipelines-unlock.yml b/.github/workflows/pipelines-unlock.yml
--- a/.github/workflows/pipelines-unlock.yml
+++ b/.github/workflows/pipelines-unlock.yml
@@ -180,7 +180,11 @@ jobs:
             export AWS_SECRET_ACCESS_KEY=$(jq -r '.awsCredentials.SECRET_ACCESS_KEY' <<< $auth)
             export AWS_SESSION_TOKEN=$(jq -r '.awsCredentials.SESSION_TOKEN' <<< $auth)
 
-            aws dynamodb delete-table --table-name terraform-locks || true # Ignore failures if no table already exists
+            REGIONS=$(aws ec2 describe-regions --query "Regions[].RegionName" --output text)
+
+            for region in $REGIONS; do
+              aws dynamodb delete-table --table-name terraform-locks --region $region || true # Ignore failures if no table already exists
+            done
 
             echo "Lock removed for $ACCOUNTID"
           }
