chore: pass into regular pipelines too

diff --git a/.github/workflows/pipelines.yml b/.github/workflows/pipelines.yml
--- a/.github/workflows/pipelines.yml
+++ b/.github/workflows/pipelines.yml
@@ -39,12 +39,26 @@ jobs:
     runs-on: ${{ fromJSON(inputs.runner) }}
     steps:
       - name: Checkout Pipelines Actions
+        id: checkout_actions
         uses: actions/checkout@v4
         with:
           path: pipelines-actions
           repository: gruntwork-io/pipelines-actions
           ref: ${{ env.PIPELINES_ACTIONS_VERSION }}
           token: ${{ secrets.PIPELINES_READ_TOKEN }}
+
+      - name: Validate PIPELINES_READ_TOKEN
+        if: always() && steps.checkout_actions.conclusion != 'success'
+        env:
+          GH_TOKEN: ${{ github.token }}
+          GITHUB_ORG: ${{ github.repository }}
+        shell: bash
+        run: |
+          msg="Failed to checkout Pipelines Actions repository. Please check to ensure PIPELINES_READ_TOKEN is valid and unexpired. More info at https://docs.gruntwork.io/pipelines/security/machine-users#ci-read-only-user"
+          echo "::error:: $msg"
+          echo $msg >> "$GITHUB_STEP_SUMMARY"
+          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
+          gh pr comment $pull_number -b "$msg" -R $GITHUB_ORG  || true
 
       - name: Check out repo code
         uses: actions/checkout@v4
